### ISSUE TITLE
Every body dies...

### ISSUE THREAD

**Issue by ToBinio** [JonasPfeifer05/ChessEngine#51]
if inOrder mode is on and somebody makes a move some body other just dies with out any reason

**Comment by JonasPfeifer05** [comment]
Does it happen with the current master branch. Faced the bug one but it should have gotten fixed.

**Comment by JonasPfeifer05** [comment]
If yes pls tell me which move causes it to happen

**Comment by ToBinio** [comment]
yes it happend also in the current master branch... and every move i wasnt able to find a move with worked like expected

**Comment by JonasPfeifer05** [comment]
Weird it worked fornme lately Ill look at that

**Comment by JonasPfeifer05** [comment]
I have look at it rigth now. Before your merge into master everthing worked fine. I also saw you changed the order of the players? Maybe something related with this brang up the bug. But the bug is in your changes. Ill maybe have a look at it later, but u can also look for it. just use the bug fixing branch and create a new one from it

**Comment by JonasPfeifer05** [comment]
fixed! Function look for the moves of a figure but the function returned an empty list, because it wasnt the players turn
